<?php
/**
 * @file
 * builder_product_export.features.uuid_node.inc
 */

/**
 * Implements hook_uuid_features_default_content().
 */
function builder_product_export_uuid_features_default_content() {
  $nodes = array();

  $nodes[] = array(
  'uid' => 851,
  'title' => 'Drupal Business Theme - Builder',
  'log' => '',
  'status' => 0,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '46904ff9-7cef-4015-8597-0ede7d0799f5',
  'type' => 'template_display',
  'language' => 'und',
  'created' => 1389411832,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '447c8236-2c77-482d-bb70-892c4afcfcd8',
  'revision_uid' => 851,
  'field_product' => array(
    'und' => array(
      0 => array(
        'product_id' => 145,
      ),
      1 => array(
        'product_id' => 146,
      ),
      2 => array(
        'product_id' => 147,
      ),
      3 => array(
        'product_id' => 148,
      ),
      4 => array(
        'product_id' => 149,
      ),
      5 => array(
        'product_id' => 150,
      ),
    ),
  ),
  'field_line_item' => array(),
  'field_description_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Business Theme Drupal BEAUTIFUL & ELEGANT',
        'format' => NULL,
        'safe_value' => 'Business Theme Drupal BEAUTIFUL &amp; ELEGANT',
      ),
    ),
  ),
  'field_keywords_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'drupal business theme, business theme drupal, drupal business themes, business drupal theme, business drupal themes, business theme drupal 7, corporate clean drupal theme, corporate clean theme drupal',
        'format' => NULL,
        'safe_value' => 'drupal business theme, business theme drupal, drupal business themes, business drupal theme, business drupal themes, business theme drupal 7, corporate clean drupal theme, corporate clean theme drupal',
      ),
    ),
  ),
  'field_title_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Business Theme - Builder',
        'format' => NULL,
        'safe_value' => 'Drupal Business Theme - Builder',
      ),
    ),
  ),
  'field_designer_partnership' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
      ),
    ),
  ),
  'field_design_url' => array(),
  'name' => 'margots',
  'picture' => 0,
  'data' => NULL,
  'date' => '2014-01-11 03:43:52 +0000',
);
  $nodes[] = array(
  'uid' => 851,
  'title' => 'Drupal Admin Theme - Cascade',
  'log' => '',
  'status' => 0,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => 'af45d78e-0978-4d6e-affd-777ca17bb584',
  'type' => 'template_display',
  'language' => 'und',
  'created' => 1389457584,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '5fdf7b58-7828-46b5-a3c6-46d4cc38fad4',
  'revision_uid' => 851,
  'field_product' => array(
    'und' => array(
      0 => array(
        'product_id' => 151,
      ),
      1 => array(
        'product_id' => 152,
      ),
      2 => array(
        'product_id' => 153,
      ),
    ),
  ),
  'field_line_item' => array(),
  'field_description_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Admin Theme - PRACTICAL & MODERN',
        'format' => NULL,
        'safe_value' => 'Drupal Admin Theme - PRACTICAL &amp; MODERN',
      ),
    ),
  ),
  'field_keywords_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'drupal admin theme,  drupal admin themes, best drupal admin theme, best drupal admin themes, drupal hosting theme',
        'format' => NULL,
        'safe_value' => 'drupal admin theme,  drupal admin themes, best drupal admin theme, best drupal admin themes, drupal hosting theme',
      ),
    ),
  ),
  'field_title_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Admin Theme ',
        'format' => NULL,
        'safe_value' => 'Drupal Admin Theme ',
      ),
    ),
  ),
  'field_designer_partnership' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
      ),
    ),
  ),
  'field_design_url' => array(),
  'name' => 'margots',
  'picture' => 0,
  'data' => NULL,
  'date' => '2014-01-11 16:26:24 +0000',
);
  $nodes[] = array(
  'uid' => 851,
  'title' => 'Drupal Admin Theme - Ace',
  'log' => '',
  'status' => 0,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '43ef9f67-6b9b-44cc-b51a-04249d674401',
  'type' => 'template_display',
  'language' => 'und',
  'created' => 1389479056,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '7d6f416e-356b-4b9c-891b-ecbff2c8fc88',
  'revision_uid' => 851,
  'field_product' => array(
    'und' => array(
      0 => array(
        'product_id' => 160,
      ),
      1 => array(
        'product_id' => 161,
      ),
      2 => array(
        'product_id' => 162,
      ),
    ),
  ),
  'field_line_item' => array(),
  'field_description_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Admin Theme RICH WITH WIDGETS WHILE BUILD TO AMAZE',
        'format' => NULL,
        'safe_value' => 'Drupal Admin Theme RICH WITH WIDGETS WHILE BUILD TO AMAZE',
      ),
    ),
  ),
  'field_keywords_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'drupal admin theme, drupal admin themes, best drupal admin theme, best drupal admin themes, drupal hosting theme',
        'format' => NULL,
        'safe_value' => 'drupal admin theme, drupal admin themes, best drupal admin theme, best drupal admin themes, drupal hosting theme',
      ),
    ),
  ),
  'field_title_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Admin Theme - ACE',
        'format' => NULL,
        'safe_value' => 'Drupal Admin Theme - ACE',
      ),
    ),
  ),
  'field_designer_partnership' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
      ),
    ),
  ),
  'field_design_url' => array(),
  'name' => 'margots',
  'picture' => 0,
  'data' => NULL,
  'date' => '2014-01-11 22:24:16 +0000',
);
  $nodes[] = array(
  'uid' => 851,
  'title' => 'Drupal Company Theme - Calypso',
  'log' => '',
  'status' => 0,
  'comment' => 0,
  'promote' => 0,
  'sticky' => 0,
  'vuuid' => '4fc6fdf7-fcd6-453f-9437-450f9fa54e5e',
  'type' => 'template_display',
  'language' => 'und',
  'created' => 1389464047,
  'tnid' => 0,
  'translate' => 0,
  'uuid' => '821f389e-7edf-4611-a9c3-22b081b2d9a7',
  'revision_uid' => 851,
  'field_product' => array(
    'und' => array(
      0 => array(
        'product_id' => 154,
      ),
      1 => array(
        'product_id' => 155,
      ),
      2 => array(
        'product_id' => 156,
      ),
      3 => array(
        'product_id' => 159,
      ),
      4 => array(
        'product_id' => 158,
      ),
      5 => array(
        'product_id' => 157,
      ),
    ),
  ),
  'field_line_item' => array(),
  'field_description_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Company Theme Drupal Business Theme AESTHETIC & PRACTICAL',
        'format' => NULL,
        'safe_value' => 'Drupal Company Theme Drupal Business Theme AESTHETIC &amp; PRACTICAL',
      ),
    ),
  ),
  'field_keywords_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'drupal themes corporate clean, drupal themes for business, drupal company theme, drupal 7 business theme, drupal 7 corporate themes, drupal business template, drupal business theme, business theme drupal, drupal business themes, business drupal theme',
        'format' => NULL,
        'safe_value' => 'drupal themes corporate clean, drupal themes for business, drupal company theme, drupal 7 business theme, drupal 7 corporate themes, drupal business template, drupal business theme, business theme drupal, drupal business themes, business drupal theme',
      ),
    ),
  ),
  'field_title_seo' => array(
    'und' => array(
      0 => array(
        'value' => 'Drupal Company Theme',
        'format' => NULL,
        'safe_value' => 'Drupal Company Theme',
      ),
    ),
  ),
  'field_designer_partnership' => array(
    'und' => array(
      0 => array(
        'tid' => 46,
      ),
    ),
  ),
  'field_design_url' => array(),
  'name' => 'margots',
  'picture' => 0,
  'data' => NULL,
  'date' => '2014-01-11 18:14:07 +0000',
);
  return $nodes;
}
